font_name: academicons
version: 1.9.3
css_selector: .ai-{{glyph}}
preprocessor_path: ""
autowidth: true
no_hash: true
force: false
debug: false
quiet: false

copyright: |
  Academicons by James Walsh (https://github.com/jpswalsh) and Katja Bercic (https://github.com/katjabercic)

  The Academicons font is licensed under the SIL OFL 1.1 (http://scripts.sil.org/OFL).
  Academicons CSS, LESS, and SASS files are licensed under the MIT License (http://opensource.org/licenses/mit-license.html).
  The Academicons documentation is licensed under the CC BY 3.0 License (http://creativecommons.org/licenses/by/3.0/)

  Square icons designed to be used alongside Font Awesome square icons

font_design_size: 16
font_em: 512
font_ascent: 448
font_descent: 64

input:
  vectors: svg
  templates: config

templates:
  - academicons.css
  - preview
  - unicode.md
  - index.md
  - table.html

output:
  fonts: academicons/fonts
  css: academicons/css
  preview: academicons
  unicode.md: academicons/docs
  index.md: academicons/docs
  kitchen-sink.md: academicons/docs
  table.html: academicons/test
